### ISSUE TITLE
HTML Hyperlinks

### ISSUE THREAD

**Issue by cyouh95** [arturopfp/tea-cozy#2]
Great use of hyperlinks in your menu bar to link to the different sections of your page!
https://github.com/arturopfp/tea-cozy/blob/9630fbb64f92846268195e637cc4506ffe9b1bb1/index.html#L17-L19

Though it seems you are missing the `mission` _id_ here for the first section:
https://github.com/arturopfp/tea-cozy/blob/master/index.html#L28

**Comment by arturopfp** [comment]
Thanks for the notices, I will fix that for sure !
