### ISSUE TITLE
Linking Images

### ISSUE THREAD

**Issue by cyouh95** [arturopfp/tea-cozy#3]
Great job linking images in both your [stylesheet](https://github.com/arturopfp/tea-cozy/blob/master/css/main.css#L64) and [HTML](https://github.com/arturopfp/tea-cozy/blob/master/index.html#L13)!

Although it seems you are missing the `background-image` for the location section here: https://github.com/arturopfp/tea-cozy/blob/master/index.html#L64-L86

**Comment by arturopfp** [comment]
I dont know what happened ! I'll fix that as soon as posible
